[build]
  publish = "dist/noe-estudio/browser"
  command = "npm run build"

[[redirects]]
  from = "https://bruzzeseyasociados.netlify.app"
  to = "https://bruzzeseyasociados.netlify.app/home"
  status = 301
